import { createAdminClient } from "@/lib/supabase/admin";

/**
 * Meta Marketing API (Insights) — per-club connection.
 *
 * Round 47 (30 сен 2026): every club connects its OWN ad account with a
 * token generated by a system user in the club's OWN business portfolio
 * (see docs/meta-ads-partner-guide in the project). Deliberately no
 * central WiClub business portfolio / app in between — HQ's Meta profiles
 * are ad-restricted, and linking partners' ad accounts to a restricted
 * business could spread the restriction to them. The token only needs
 * `ads_read` and is stored in meta_ad_connections, a table with RLS on and
 * no policies at all, so only this server-side code (service role) ever
 * reads it — it never reaches the browser.
 */

export const META_GRAPH_VERSION = "v23.0";
const GRAPH = `https://graph.facebook.com/${META_GRAPH_VERSION}`;

/** First sync pulls this far back; every later sync re-pulls the last
 * RESYNC_DAYS because Meta keeps attributing conversions after the fact. */
const INITIAL_DAYS = 180;
const RESYNC_DAYS = 28;

/** Lead Ads form submissions show up under one of these action types,
 * depending on placement/attribution — the largest one is the real count
 * (they overlap, so summing would double-count). */
const LEAD_ACTION_TYPES = ["lead", "onsite_conversion.lead_grouped", "leadgen_grouped"];

export function normalizeAdAccountId(raw: string): string | null {
  const digits = raw.trim().replace(/^act_/i, "").replace(/\s+/g, "");
  return /^\d{5,}$/.test(digits) ? digits : null;
}

type GraphError = { error?: { message?: string; code?: number } };

async function graphGet<T>(path: string, params: Record<string, string>, token: string): Promise<T> {
  const url = new URL(path.startsWith("http") ? path : `${GRAPH}/${path}`);
  if (!path.startsWith("http")) {
    for (const [k, v] of Object.entries(params)) url.searchParams.set(k, v);
  }
  const res = await fetch(url, {
    headers: { Authorization: `Bearer ${token}` },
    cache: "no-store",
  });
  const body = (await res.json().catch(() => ({}))) as T & GraphError;
  if (!res.ok || body.error) {
    throw new Error(body.error?.message ?? `Meta API HTTP ${res.status}`);
  }
  return body;
}

/** Validates the token against the ad account before saving — a typo'd id
 * or a token without access fails here, not silently at the first sync. */
export async function fetchAdAccountInfo(
  adAccountId: string,
  token: string
): Promise<{ name: string; currency: string }> {
  const info = await graphGet<{ name?: string; currency?: string }>(
    `act_${adAccountId}`,
    { fields: "name,currency,account_status" },
    token
  );
  return { name: info.name ?? `act_${adAccountId}`, currency: info.currency ?? "USD" };
}

type InsightRow = {
  date_start: string;
  campaign_id: string;
  campaign_name?: string;
  spend?: string;
  impressions?: string;
  clicks?: string;
  actions?: { action_type: string; value: string }[];
};

function leadsFromActions(actions: InsightRow["actions"]): number {
  if (!actions) return 0;
  let best = 0;
  for (const a of actions) {
    if (LEAD_ACTION_TYPES.includes(a.action_type)) best = Math.max(best, Number(a.value) || 0);
  }
  return best;
}

function isoDay(d: Date): string {
  return d.toISOString().slice(0, 10);
}

async function fetchDailyCampaignInsights(
  adAccountId: string,
  token: string,
  since: string,
  until: string
): Promise<InsightRow[]> {
  const rows: InsightRow[] = [];
  let page = await graphGet<{ data: InsightRow[]; paging?: { next?: string } }>(
    `act_${adAccountId}/insights`,
    {
      level: "campaign",
      time_increment: "1",
      time_range: JSON.stringify({ since, until }),
      fields: "campaign_id,campaign_name,spend,impressions,clicks,actions",
      limit: "500",
    },
    token
  );
  rows.push(...page.data);
  // Hard cap on pages so a misbehaving cursor can never loop forever.
  for (let i = 0; i < 50 && page.paging?.next; i++) {
    page = await graphGet(page.paging.next, {}, token);
    rows.push(...page.data);
  }
  return rows;
}

/**
 * Pulls insights for one club and upserts them into ad_insights_daily.
 * Records the outcome (last_sync_at / last_sync_error) on the connection
 * either way, so the page can show "last updated" or the real Meta error
 * instead of silently stale numbers.
 */
export async function syncPartnerMetaAds(partnerId: string): Promise<{ ok: true; rows: number } | { ok: false; error: string }> {
  const admin = createAdminClient();
  const { data: conn } = await admin
    .from("meta_ad_connections")
    .select("*")
    .eq("partner_id", partnerId)
    .maybeSingle();
  if (!conn) return { ok: false, error: "adsErrNotConnected" };

  const until = new Date();
  const since = new Date();
  since.setUTCDate(since.getUTCDate() - (conn.last_sync_at ? RESYNC_DAYS : INITIAL_DAYS));

  try {
    const rows = await fetchDailyCampaignInsights(conn.ad_account_id, conn.access_token, isoDay(since), isoDay(until));
    const now = new Date().toISOString();
    const records = rows.map((r) => ({
      partner_id: partnerId,
      date: r.date_start,
      campaign_id: r.campaign_id,
      campaign_name: r.campaign_name ?? null,
      spend: Number(r.spend ?? 0),
      impressions: Number(r.impressions ?? 0),
      clicks: Number(r.clicks ?? 0),
      leads: leadsFromActions(r.actions),
      currency: conn.account_currency,
      updated_at: now,
    }));
    for (let i = 0; i < records.length; i += 500) {
      const { error } = await admin
        .from("ad_insights_daily")
        .upsert(records.slice(i, i + 500), { onConflict: "partner_id,date,campaign_id" });
      if (error) throw new Error(error.message);
    }
    await admin
      .from("meta_ad_connections")
      .update({ last_sync_at: now, last_sync_error: null, updated_at: now })
      .eq("partner_id", partnerId);
    return { ok: true, rows: records.length };
  } catch (e) {
    const message = e instanceof Error ? e.message : String(e);
    await admin
      .from("meta_ad_connections")
      .update({ last_sync_error: message, updated_at: new Date().toISOString() })
      .eq("partner_id", partnerId);
    return { ok: false, error: message };
  }
}
